#!/bin/busybox sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

ROOT_DEV="/dev/mmcblk0p2"
ROOT_MOUNT="/mnt/root"
ROOT_IMAGE="rootfs.img"
MOUNT="/bin/mount"
UMOUNT="/bin/umount"
ISOLINUX=""

ROOT_DISK=""

# Create the default busybox command tree with all the soft links etc
/bin/busybox --install -s

echo "Running initramfs init script"

# Copied from initramfs-framework. The core of this script probably should be
# turned into initramfs-framework modules to reduce duplication.
#
# Adapted for BGRxxx by Jon Considine, for Access-IS, 2016
# TBD - detect u-boot parameter indicating secret switch pressed and boot kernel from USB stick in this case
#

udev_daemon() {
	OPTIONS="/sbin/udev/udevd /sbin/udevd /lib/udev/udevd /lib/systemd/systemd-udevd"

	for o in $OPTIONS; do
		if [ -x "$o" ]; then
			echo $o
			return 0
		fi
	done

	return 1
}

_UDEV_DAEMON=`udev_daemon`

early_setup() {
    mkdir -p /proc
    mkdir -p /sys
    mount -t proc proc /proc
    mount -t sysfs sysfs /sys
    mount -t devtmpfs none /dev

    # support modular kernel
    # modprobe isofs 2> /dev/null

    mkdir -p /run
    mkdir -p /var/run
}

read_args() {
    [ -z "$CMDLINE" ] && CMDLINE=`cat /proc/cmdline`
    for arg in $CMDLINE; do
        optarg=`expr "x$arg" : 'x[^=]*=\(.*\)'`
        case $arg in
            root=*)
                ROOT_DEVICE=$optarg ;;
            rootimage=*)
                ROOT_IMAGE=$optarg ;;
            rootfstype=*)
                modprobe $optarg 2> /dev/null ;;
            LABEL=*)
                label=$optarg ;;
            video=*)
                video_mode=$arg ;;
            vga=*)
                vga_mode=$arg ;;
            console=*)
                if [ -z "${console_params}" ]; then
                    console_params=$arg
                else
                    console_params="$console_params $arg"
                fi ;;
            debugshell*)
                if [ -z "$optarg" ]; then
                        shelltimeout=30
                else
                        shelltimeout=$optarg
                fi
        esac
    done
}

boot_live_root() {
    # Watches the udev event queue, and exits if all current events are handled
    /usr/bin/udevadm settle --timeout=3
    killall "${_UDEV_DAEMON##*/}" 2>/dev/null

    # Move the mount points of some filesystems over to
    # the corresponding directories under the real root filesystem.
    for dir in `awk '/\/dev.* \/run\/media/{print $2}' /proc/mounts`; do
        mkdir -p  ${ROOT_MOUNT}/media/${dir##*/}
        mount -n --move $dir ${ROOT_MOUNT}/media/${dir##*/}
    done
    mount -n --move /proc ${ROOT_MOUNT}/proc
    mount -n --move /sys ${ROOT_MOUNT}/sys
    mount -n --move /dev ${ROOT_MOUNT}/dev

    cd $ROOT_MOUNT

    # busybox switch_root supports -c option
    exec switch_root -c /dev/console $ROOT_MOUNT /sbin/init $CMDLINE ||
        fatal "Couldn't switch_root, dropping to shell"
}

fatal() {
    echo $1 >$CONSOLE
    echo >$CONSOLE
    exec sh
}


early_setup

[ -z "$CONSOLE" ] && CONSOLE="/dev/console"

read_args

# Try to mount the root image read-write and then boot it up.
# This function distinguishes between a read-only image and a read-write image.
# In the former case (typically an iso), it tries to make a union mount if possible.
# In the latter case, the root image could be mounted and then directly booted up.
# Wait for the MMC device to become ready before proceeding, with 3 second timeout. -JWC
mount_and_boot() {
    mkdir -p $ROOT_MOUNT
    mknod /dev/loop0 b 7 0 2>/dev/null

    COUNTER=0
    while [ $COUNTER -lt 30 ] && [ ! -b $ROOT_DEV ] ; do
        usleep 100000
        let COUNTER=COUNTER+1
    done
    echo "MMC detected"

    if ! mount -o rw,noatime,nodiratime,data=journal,commit=1 $ROOT_DEV $ROOT_MOUNT ; then
	fatal "Could not mount rootfs"
    fi

# For BGR750 we want to mount overlayfs regardless if whether it's RW/RO
#    if touch $ROOT_MOUNT/bin 2>/dev/null; then
#	# The root image is read-write, directly boot it up.
#	boot_live_root
#   fi

# determine which unification filesystem to use
# for BGR750 always use overlayfs because it's more efficient than aufs and
# in mainstream kernel from 3.18 onwards
    if grep -q -w "overlayfs" /proc/filesystems; then
	union_fs_type="overlayfs"
    elif grep -q -w "aufs" /proc/filesystems; then
	union_fs_type="aufs"
    else
	union_fs_type=""
    fi

    # make a union mount if possible
    case $union_fs_type in
	"overlayfs")
	    mkdir -p /rootfs.lower /rootfs.upper
	    if ! mount -n --move $ROOT_MOUNT /rootfs.lower; then
		rm -rf /rootfs.lower /rootfs.upper
		fatal "Could not move rootfs mount point"
	    else
		mount -t tmpfs -o rw,noatime,mode=755 tmpfs /rootfs.upper
		mount -t overlayfs -o "lowerdir=/rootfs.lower,upperdir=/rootfs.upper" overlayfs $ROOT_MOUNT
		mkdir -p $ROOT_MOUNT/rootfs.lower $ROOT_MOUNT/rootfs.upper
		mount --move /rootfs.lower $ROOT_MOUNT/rootfs.lower
		mount --move /rootfs.upper $ROOT_MOUNT/rootfs.upper
	    fi
	    ;;
	"aufs")
	    mkdir -p /rootfs.lower /rootfs.upper
	    if ! mount -n --move $ROOT_MOUNT /rootfs.lower; then
		rm -rf /rootfs.lower /rootfs.upper
		fatal "Could not move rootfs mount point"
	    else
		mount -t tmpfs -o rw,noatime,mode=755 tmpfs /rootfs.upper
		mount -t aufs -o "dirs=/rootfs.upper=rw:/rootfs.lower=ro" aufs $ROOT_MOUNT
		mkdir -p $ROOT_MOUNT/rootfs.lower $ROOT_MOUNT/rootfs.upper
		mount --move /rootfs.lower $ROOT_MOUNT/rootfs.lower
		mount --move /rootfs.upper $ROOT_MOUNT/rootfs.upper
	    fi
	    ;;
	"")
	    mount -t tmpfs -o rw,noatime,mode=755 tmpfs $ROOT_MOUNT/media
	    ;;
    esac

    # boot the image
    boot_live_root
}

echo 'Booting'
mount_and_boot

# Drops through here if rootfs fails to mount
echo "Waiting for removable media..."
C=0
while true
do
  for i in `ls /run/media 2>/dev/null`; do
      if [ -f /run/media/$i/$ROOT_IMAGE ] ; then
		found="yes"
		ROOT_DISK="$i"
		break
	  elif [ -f /run/media/$i/isolinux/$ROOT_IMAGE ]; then
		found="yes"
		ISOLINUX="isolinux"
		ROOT_DISK="$i"
		break
      fi
  done
  if [ "$found" = "yes" ]; then
      break;
  fi
  # don't wait for more than $shelltimeout seconds, if it's set
  if [ -n "$shelltimeout" ]; then
      echo -n " " $(( $shelltimeout - $C ))
      if [ $C -ge $shelltimeout ]; then
           echo "..."
	   echo "Mounted filesystems"
           mount | grep media
           echo "Available block devices"
           cat /proc/partitions
           fatal "Cannot find $ROOT_IMAGE file in /run/media/* , dropping to a shell "
      fi
      C=$(( C + 1 ))
  fi
  sleep 1
done

if [ "$label" != "boot" -a -f $label.sh ] ; then
	if [ -f /run/media/$i/$ISOLINUX/$ROOT_IMAGE ] ; then
	    ./$label.sh $i/$ISOLINUX $ROOT_IMAGE $video_mode $vga_mode $console_params
	else
	    fatal "Could not find $label script"
	fi

	# If we're getting here, we failed...
	fatal "Target $label failed"
fi

mount_and_boot
